language: cpp

script:
  - scripts/build-SFML
  - scripts/cmake-makefile

matrix:
  include:
    - os: osx
      osx_image: xcode9.3

    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - g++
            - libx11-dev
            - libgl1-mesa-dev
            - libudev-dev
            - libopenal-dev
            - libflac-dev
            - libvorbis-dev
            - libflac-dev
            - libxrandr-dev
            - libfreetype6-dev