sudo: required
language: generic
dist: xenial

before_install:
  - sudo rm -rf target
  - mkdir target
  - sudo scripts/build-SFML

script:
  - scripts/cmake-makefile

matrix:
  include:
    - os: osx
      osx_image: xcode9.3

    # - os: linux
    #   env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
    #   addons:
    #     apt:
    #       packages:
    #         - g++-5
    #         - cmake
    #         - libflac-dev
    #         - libfreetype6-dev
    #         - libgl1-mesa-dev
    #         - libjpeg-dev
    #         - libopenal-dev
    #         - libudev-dev
    #         - libvorbis-dev
    #         - libx11-dev
    #         - libxrandr-dev

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
            - libflac-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libjpeg-dev
            - libopenal-dev
            - libudev-dev
            - libvorbis-dev
            - libx11-dev
            - libxrandr-dev