#!/usr/bin/env bash

set -e
set -x

cd $(dirname $0)/..
ROOTDIR="$(pwd)"

rm -rf target/vendor/SFML
mkdir -p target/vendor/SFML
cd target/vendor/SFML

# apt install -y cmake g++ libx11-dev libxrandr-dev libgl1-mesa-dev libudev-dev libjpeg-dev libopenal-dev libflac-dev libvorbis-dev libfreetype6-dev
# apt install -y cmake-curses-gui

cmake ../../../vendor/SFML \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_BUILD_TYPE=Debug \
	-DSFML_BUILD_EXAMPLES=OFF \
	-DSFML_BUILD_FRAMEWORKS=OFF

make
make install